services:
    coursemap:
        image: ghcr.io/allanhechen/coursemap:latest
        environment:
            DEPLOYMENT_TYPE: ${DEPLOYMENT_TYPE:-docker}
            POSTGRES_URL: ${POSTGRES_URL:-postgresql://postgres:password@postgres:5432/postgres}
            AUTH_URL: http://localhost:3000/api/auth
            AUTH_TRUST_HOST: 1
        ports:
            - "3000:3000"
        depends_on:
            - pg_proxy
        env_file:
            - .env
    postgres:
        image: postgres:16.4
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        ports:
            - "54320:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        env_file:
            - .env
    pg_proxy:
        image: ghcr.io/neondatabase/wsproxy:latest
        environment:
            ALLOW_ADDR_REGEX: ".*"
            LOG_TRAFFIC: "true"
        ports:
            - "54330:80"
        depends_on:
            - postgres
