services:
    coursemap:
        build: .
        environment:
            DEPLOYMENT_TYPE: ${DEPLOYMENT_TYPE:-docker}
            POSTGRES_URL: ${POSTGRES_URL:-postgresql://postgres:password@postgres:5432/postgres}
        ports:
            - "3000:3000"
        depends_on:
            - pg_proxy
    postgres:
        image: postgres:16.4
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        ports:
            - "54320:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
    pg_proxy:
        image: ghcr.io/neondatabase/wsproxy:latest
        environment:
            APPEND_PORT: ${APPEND_PORT:-}
            ALLOW_ADDR_REGEX: ".*"
            LOG_TRAFFIC: "true"
        ports:
            - "54330:80"
        depends_on:
            - postgres
