import type { Metadata } from "next";

import "@xyflow/react/dist/style.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@/app/(main)/globals.css";

import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";

const theme = createTheme({
    primaryShade: { light: 6, dark: 4 },
    primaryColor: "blue",

    white: "#FFFFFF",
    black: "#22242E",
    defaultRadius: "10px",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript defaultColorScheme="dark" />
            </head>
            <body>
                <MantineProvider theme={theme} defaultColorScheme="dark">
                    {children}
                </MantineProvider>
            </body>
        </html>
    );
}
